CREATE SCHEMA IF NOT EXISTS TIMELY AUTHORIZATION postgres;

CREATE SEQUENCE IF NOT EXISTS TIMELY.TIMELY_ID_SEQ
	START WITH 1  INCREMENT BY 1   NO CYCLE CACHE 1;
	
CREATE TABLE IF NOT EXISTS TIMELY.TIMELY
(
	ID       BIGINT NOT NULL DEFAULT nextval ('TIMELY.TIMELY_ID_SEQ'),
	PROJECT  VARCHAR(255),
	START	 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
	STOP     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DURATION BIGINT
) TABLESPACE PG_DEFAULT